// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsfpdhhayhjqbkcjqniv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZnBkaGhheWhqcWJrY2pxbml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTEwMDYsImV4cCI6MjA2NDE4NzAwNn0.ksQ8eiVANq-g0a1_ZhDajScqwsB3YwgoSdBjk2fYTwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);